[build]
  publish = "."
  functions = "netlify/functions"

[build.processing]
  skip_processing = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
